on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Build binary (Windows)
        shell: powershell
        run: "cargo build --release --target x86_64-pc-windows-msvc"
      - name: Package as archive
        shell: bash
        run: |
          cd target/x86_64-pc-windows-msvc/release
          7z a ../../../windows.zip grayfruit.exe
          cd -
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: grayfruit
          path: "windows.zip"
